# Generated by Django 5.1.9 on 2025-05-13 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NHI', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(choices=[('INP', 'Inpatient'), ('OUT', 'Outpatient'), ('ED', 'Emergency'), ('PRI', 'Private'), ('ACC', 'ACC')], max_length=10)),
                ('accession_number', models.CharField(max_length=20, unique=True)),
                ('modality', models.CharField(choices=[('XR', 'X-Ray'), ('CT', 'CT'), ('MRI', 'MRI'), ('US', 'Ultrasound'), ('NM', 'Nuclear Medicine'), ('FL', 'Fluoroscopy')], max_length=10)),
                ('clinical_info', models.TextField()),
                ('study_requested', models.CharField(max_length=50)),
                ('urgency', models.CharField(choices=[('Immediate', 'Immediate'), ('<1 hour', '<1 hour'), ('<4 hours', '<4 hours'), ('<24 hours', '<24 hours'), ('<2 weeks', '<2 weeks'), ('<4 weeks', '<4 weeks'), ('Planned', 'Planned')], max_length=10)),
                ('referrer_name', models.CharField(max_length=50)),
                ('referrer_team', models.CharField(max_length=50)),
                ('referrer_contact', models.CharField(blank=True, max_length=50)),
                ('received_datetime', models.DateTimeField(auto_now_add=True)),
                ('triaged_protocol', models.CharField(blank=True, max_length=50)),
                ('triaged_category', models.CharField(blank=True, choices=[('Immediate', 'Immediate'), ('<1 hour', '<1 hour'), ('<4 hours', '<4 hours'), ('<24 hours', '<24 hours'), ('<2 weeks', '<2 weeks'), ('<4 weeks', '<4 weeks'), ('Planned', 'Planned')], max_length=50)),
                ('triaged_by', models.CharField(blank=True, max_length=50)),
                ('triaged_datetime', models.DateTimeField(auto_now=True)),
                ('appointment_datetime', models.DateTimeField(blank=True, null=True)),
                ('appointment_location', models.CharField(blank=True, max_length=50)),
                ('study_completed_datetime', models.DateTimeField(blank=True, null=True)),
                ('tech_initials', models.CharField(blank=True, max_length=50)),
                ('report', models.TextField(blank=True)),
                ('rad_initials', models.CharField(blank=True, max_length=50)),
                ('results_notified', models.CharField(blank=True, max_length=50)),
                ('results_notified_datetime', models.DateTimeField(blank=True, null=True)),
                ('tech_comments', models.TextField(blank=True)),
                ('radiologist_comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Triaged', 'Triaged'), ('Waitlisted', 'Waitlisted'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Reported', 'Reported'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
